name: Python CI

on:
  push:
    branches:
      - main
      - '*/**'
  pull_request:
    branches:
      - main
      - '*/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Static Code Analysis (Linting)
        run: |
          pip install flake8
          flake8 . --exclude=venv --statistics
        
      - name: Run Tests
        run: |
          pip install pytest
          pytest
        
      - name: Security Check
        run: |
          pip install bandit
          bandit -r .

      - name: Code Coverage
        run: |
          pip install coverage
          coverage run -m pytest
          coverage report -m
